/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2024-01-12 22:38:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

				Class.forName("com.mysql.cj.jdbc.Driver");
				Connection conexion2 = null;
				if(request.getParameter("titulo") != null){
					try{
						String url = "jdbc:mysql://localhost:3306/blogjee";
						String usuario = "blogjee";
						String contrasena = "blogjee";
						
						conexion2 = DriverManager.getConnection(url,usuario,contrasena);
						
						String peticionisercion = "INSERT INTO entradas VALUES(NULL,'"+request.getParameter("titulo")+"','"+request.getParameter("contenido")+"','"+request.getParameter("fecha")+"','"+request.getParameter("autor")+"','"+request.getParameter("imagen")+"','"+request.getParameter("categoria")+"','"+request.getParameter("palabrasclave")+"')";
						PreparedStatement inserto = conexion2.prepareStatement(peticionisercion);
						inserto.executeUpdate();
						
					}catch(Exception e){
						e.printStackTrace();
					}finally{
						if(conexion2 != null){
							conexion2.close();
						}
					}
				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>Panel de control</h1>\r\n");
      out.write("\t<table border=1>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Identificador</th>\r\n");
      out.write("\t\t\t\t<th>titulo</th>\r\n");
      out.write("\t\t\t\t<th>contenido</th>\r\n");
      out.write("\t\t\t\t<th>fecha</th>\r\n");
      out.write("\t\t\t\t<th>autor</th>\r\n");
      out.write("\t\t\t\t<th>imagen</th>\r\n");
      out.write("\t\t\t\t<th>categoria</th>\r\n");
      out.write("\t\t\t\t<th>palabras clave</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t");

				Class.forName("com.mysql.cj.jdbc.Driver");
				Connection conexion = null;
				
				try{
					String url = "jdbc:mysql://localhost:3306/blogjee";
					String usuario = "blogjee";
					String contrasena = "blogjee";
					
					conexion = DriverManager.getConnection(url,usuario,contrasena);
					
					Statement peticion = conexion.createStatement();
					ResultSet resultados = peticion.executeQuery("SELECT * FROM entradas");
					
					while(resultados.next()){
						out.println(""+
								"<tr>"+
									"<td>"+resultados.getInt("Identificador")+"</td>"+
									"<td>"+resultados.getString("titulo")+"</td>"+
									"<td>"+resultados.getString("contenido")+"</td>"+
									"<td>"+resultados.getString("fecha")+"</td>"+
									"<td>"+resultados.getString("autor")+"</td>"+
									"<td>"+resultados.getString("imagen")+"</td>"+
									"<td>"+resultados.getString("categoria")+"</td>"+
									"<td>"+resultados.getString("palabrasclave")+"</td>"+
								"</tr>"+
								"");
					}
					
				}catch(Exception e){
					e.printStackTrace();
				}finally{
					if(conexion != null){
						conexion.close();
					}
				}
			
      out.write("\r\n");
      out.write("\t\t\t<form action=\"?\" method=\"POST\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"titulo\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"contenido\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"fecha\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"autor\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"imagen\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"categoria\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"text\" name=\"palabrasclave\"></th>\r\n");
      out.write("\t\t\t\t<th><input type=\"submit\"></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
